-- BOARD 테이블 샘플데이터
INSERT INTO BOARD VALUES(
    SEQ_BOARD_NO.NEXTVAL, '스프링 테스트', '테스트 내용 입니다.', 
    DEFAULT, DEFAULT, DEFAULT, DEFAULT, 1, 1
);

-- 이미지 샘플 데이터
INSERT INTO BOARD_IMG VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/sample1.jpg', 'sample1.jpg', 0, SEQ_BOARD_NO.CURRVAL);
INSERT INTO BOARD_IMG VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/sample2.jpg', 'sample1.jpg', 1, SEQ_BOARD_NO.CURRVAL);
INSERT INTO BOARD_IMG VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/sample3.jpg', 'sample1.jpg', 2, SEQ_BOARD_NO.CURRVAL);
INSERT INTO BOARD_IMG VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/sample4.jpg', 'sample1.jpg', 3, SEQ_BOARD_NO.CURRVAL);
INSERT INTO BOARD_IMG VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/sample5.jpg', 'sample1.jpg', 4, SEQ_BOARD_NO.CURRVAL);

commit;

-- 제약 조건 삭제
ALTER TABLE BOARD
DROP CONSTRAINT FK_BOARD_MEMBER;

ALTER TABLE BOARD_IMG
DROP CONSTRAINT SYS_C0018870;

-- BOARD 테이블에서 1번회원이 작성하지 않은 글 삭제
DELETE FROM BOARD
WHERE MEMBER_NO != 1;

-- 제약조건 추가(BOARD -> MEMBER_S)
ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_MEMBER_S
FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER_S
ON DELETE SET NULL;

ALTER TABLE BOARD_IMG
ADD CONSTRAINT FK_BOARD_BOARD_IMG
FOREIGN KEY(BOARD_NO)
REFERENCES BOARD
ON DELETE SET NULL;

DELETE FROM BOARD_IMG
WHERE BOARD_NO NOT IN(
    SELECT BOARD_NO FROM BOARD
);

SELECT * FROM BOARD ORDER BY 1 DESC;
SELECT * FROM BOARD_IMG ORDER BY 1 DESC;

SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICK, READ_COUNT,
CASE WHEN SYSDATE - CREATE_DT < 1
        THEN TO_CHAR(CREATE_DT, 'HH:MI')
        ELSE TO_CHAR(CREATE_DT, 'YYYY-MM-DD')
    END CREATE_DT, 
    
    (SELECT IMG_RENAME FROM BOARD_IMG 
    WHERE BOARD.BOARD_NO = BOARD_IMG.BOARD_NO
    AND IMG_LEVEL = 0) THUMBNAIL
    
FROM BOARD
JOIN BOARD_TYPE USING(BOARD_CD)
JOIN MEMBER_S USING(MEMBER_NO)
WHERE BOARD_ST = 'N'
AND BOARD_CD = ${boardCode}
ORDER BY BOARD_NO DESC;


-- 서브쿼리를 이용한 INSERT
--> SELECT 조회 결과를 BOARD_IMG 테이블에 삽입

-- 조건 1 : 서브쿼리로 조회된 RESULT SET의 컬럼과 BOARD_IMG 컬럼명이 같아야 한다.
-- 조건 2 : UNION ALL로 합쳐진 서브쿼리에서는 시퀀스를 사용할 수 없다.

INSERT INTO BOARD_IMG

SELECT SEQ_IMG_NO.NEXTVAL IMG_NO, A.* FROM(
    SELECT --SEQ_IMG_NO.NEXTVAL IMG_NO, 
        '변경된 파일명1' IMG_RENAME, '원본 파일명1' IMG_ORIGINAL, '0' IMG_LEVEL, '1000' BOARD_NO 
    FROM DUAL

    UNION ALL

    SELECT --SEQ_IMG_NO.NEXTVAL IMG_NO, 
        '변경된 파일명2' IMG_RENAME, '원본 파일명2' IMG_ORIGINAL, '1' IMG_LEVEL, '1000' BOARD_NO 
    FROM DUAL

) A;

SELECT * FROM BOARD WHERE BOARD_NO = 1564;
SELECT * FROM BOARD_IMG WHERE BOARD_NO = 1564;

